"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { validateRubric, repairMessage } from "@/lib/rubric";
import type { NormalRubric, ValidationResult } from "@/lib/rubric";

interface Props {
  /** Fires only on success — the caller loads this straight into the editable grid. */
  onImport: (rubric: NormalRubric) => void;
}

/**
 * Paste-and-validate: the primary authoring path described in
 * docs/rubric-prompt.md — a professor generates a rubric with any chat
 * assistant, pastes the JSON reply here, and it's checked entirely
 * client-side (validateRubric is pure) before anything reaches the grid or
 * the server. On success it feeds the same editable grid below, not a
 * separate straight-to-DB import, so it can still be tweaked by hand.
 */
export function PasteImportPanel({ onImport }: Props) {
  const [text, setText] = useState("");
  const [result, setResult] = useState<ValidationResult | null>(null);

  function handleValidate() {
    let parsed: unknown;
    try {
      parsed = JSON.parse(text);
    } catch {
      setResult({
        ok: false,
        rubric: null,
        warnings: [],
        errors: [{ where: "the document", message: "That isn't valid JSON — paste the whole reply, starting with { and ending with }." }],
      });
      return;
    }
    const validated = validateRubric(parsed);
    setResult(validated);
    if (validated.ok && validated.rubric) {
      onImport(validated.rubric);
      toast.success("Imported — review and adjust below, then save.");
    }
  }

  function copyRepair() {
    const msg = result && repairMessage(result);
    if (!msg) return;
    navigator.clipboard.writeText(msg);
    toast.success("Repair message copied — paste it back to the assistant.");
  }

  return (
    <div className="space-y-3">
      <p className="text-xs text-muted-foreground">
        Paste a rubric generated by an AI assistant — no point values, just criteria and level descriptions (see
        docs/rubric-prompt.md for the prompt). It&apos;s validated here before anything is saved.
      </p>
      <Textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder='{"version": 1, "name": "...", "criteria": [...]}'
        className="min-h-[140px] font-mono text-xs"
      />
      <div className="flex items-center gap-2">
        <Button type="button" variant="outline" onClick={handleValidate} disabled={!text.trim()}>
          Validate
        </Button>
        {result?.ok && <span className="text-xs text-green-600">Valid — loaded into the editor below.</span>}
      </div>

      {result && !result.ok && (
        <div className="space-y-2 rounded-md border border-destructive/40 bg-destructive/5 p-3">
          <p className="text-xs font-medium text-destructive">Didn&apos;t validate:</p>
          <ul className="list-disc space-y-1 pl-4 text-xs text-destructive">
            {result.errors.map((e, i) => (
              <li key={i}>
                <span className="font-medium">{e.where}:</span> {e.message}
              </li>
            ))}
          </ul>
          <Button type="button" variant="outline" size="sm" onClick={copyRepair}>
            Copy repair message
          </Button>
        </div>
      )}

      {result?.ok && result.warnings.length > 0 && (
        <ul className="list-disc space-y-1 pl-4 text-xs text-muted-foreground">
          {result.warnings.map((w, i) => (
            <li key={i}>
              <span className="font-medium">{w.where}:</span> {w.message}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
